Models/ErrorViewModel.cs
namespace ejerciciosMVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
namespace Mvc.Controllers{
    public class AuthController : Controller{
        public IActionResult Index(){
            return View();
        }
        public IActionResult Login(){
            return View();
        }
        public IActionResult Registro(){
            return View();
        }        
    }
}

Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
namespace Mvc.Controllers{
    public class DashboardController : Controller{
        public IActionResult Index(){
            return View();
        }
    }
}

Controllers/ProductosController.cs
using Microsoft.AspNetCore.Mvc;
namespace Mvc.Controllers{
    public class ProductosController : Controller{
        public IActionResult Index(){
            return View();
        }
        public IActionResult MostrarProducto(){
            return View();
        }
        public IActionResult EliminarProducto(){
            return View();
        }
        public IActionResult CrearProducto(){
            return View();
        }
        public IActionResult EditarProducto(){
            return View();
        }
        public IActionResult ActualizarProducto(){
            return View();
        }
    }
}

Controllers/UserController.cs
// retornamos desde el controlador principal
using Microsoft.AspNetCore.Mvc;
//El namespace siempre se debe de llamar así
namespace Mvc.Controllers{
    //heredamos de la clase controller
    public class UserController : Controller{
        //Este método lo que nos devuelve es una vista IActionResult devuelve la vista
        public IActionResult Index(){
            return View();//a menos que sea el index la ruta se coloca dentro de los parentesis
        }
        public IActionResult Mostrar(){
            return View();
        }
        public IActionResult Eliminar(){
            return View();
        }
        public IActionResult Crear(){
            return View();
        }
        public IActionResult Editar(){
            return View();
        }
        public IActionResult Actualizar(){
            return View();
        }
    }
}

Views/Dashboard/Index.cshtml
<div class="container text-center mt-5">
    <h1>Bienvenido a mi Página Web</h1>
</div>

<div class="container h-75 text-center bg-warning-subtle">
    <a class="btn btn-info" asp-controller="Productos" asp-action="Index">Gestión de Productos</a>
    <a class="btn btn-info" asp-controller="Auth" asp-action="Index">Registrate</a>
    <a class="btn btn-info" asp-controller="User" asp-action="Index">Gestion de Usuarios</a>    
</div>

Views/Productos/ActualizarProducto.cshtml
<div class="container">
    <div class="row justify-content-end">
        <div class="col-auto">
            <a asp-controller="Dashboard" asp-action="Index">Inicio</a>
        </div>
        <div class="col-auto">
            <a class="text-decoration-none text-black" asp-controller="Productos" asp-action="CrearProducto">Crear Nuevo Producto</a>
        </div>
    </div>
</div>

<div class="container d-flex justify-content-center align-items-center">
    <div class="row">
        <div class="col-auto">
            <div class="card">
                <div class="card-body">
                    <h1>Se ha Actualizado con éxito el Producto</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container mt-3">
    <div class="row justify-content-center">
        <a type="button" class="btn btn-primary btn-lg w-25" asp-controller="Productos" asp-action="Index">Ver Lista Usuarios</a>
    </div>
</div>  

Views/Productos/CrearProducto.cshtml
<div class="container">
    <div class="row justify-content-end">
        <div class="col-auto">
            <a asp-controller="Dashboard" asp-action="Index">Inicio</a>
        </div>
        <div class="col-auto">
            <a class="text-decoration-none text-black" asp-controller="#" asp-action="#">Crear Nuevo Producto</a>
        </div>
    </div>
</div>

<form>
    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Imagen</label>
        <input type="file" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Nombre</label>
        <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Precio</label>
        <input type="number" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Cantidad</label>
        <input type="number" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>   
    <button type="submit" class="btn btn-primary" asp-controller="Productos" asp-action="CrearProducto">Crear Producto</button>
</form>

Views/Productos/EditarProducto.cshtml
<div class="container">
    <div class="row justify-content-end">
        <div class="col-auto">
            <a asp-controller="Dashboard" asp-action="Index">Inicio</a>
        </div>
        <div class="col-auto">
            <a class="text-decoration-none text-black" asp-controller="Productos" asp-action="CrearProducto">Crear Nuevo Producto</a>
        </div>
    </div>
</div>

<form>
    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Imagen</label>
        <input type="file" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Nombre</label>
        <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Precio</label>
        <input type="number" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Cantidad</label>
        <input type="number" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>   
    <button type="submit" class="btn btn-primary" asp-controller="Productos" asp-action="ActualizarProducto">Actualizar Producto</button>
</form>

Views/Productos/EliminarProducto.cshtml
<div class="container">
    <div class="row justify-content-end">
        <div class="col-auto">
            <a asp-controller="Dashboard" asp-action="Index">Inicio</a>
        </div>
        <div class="col-auto">
            <a class="text-decoration-none text-black" asp-controller="Productos" asp-action="CrearProducto">Crear Nuevo Producto</a>
        </div>
    </div>
</div>

<div class="container d-flex justify-content-center align-items-center">
    <div class="row">
        <div class="col-auto">
            <div class="card">
                <div class="card-body">
                    <h1>Se ha eliminado con éxito el producto</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container mt-3">
    <div class="row justify-content-center">
        <a type="button" class="btn btn-primary btn-lg w-25" asp-controller="Productos" asp-action="Index">Ver Lista productos</a>
    </div>
</div>

Views/Productos/Index.cshtml
<div class="container">
  <div class="row justify-content-end">
    <div class="col-auto">
      <a asp-controller="Dashboard" asp-action="Index">Inicio</a>
    </div>
    <div class="col-auto">
      <a class="text-decoration-none text-black" asp-controller="#" asp-action="#"> Gestion Productos</a>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col">
      <a class="btn btn-outline-primary" asp-controller="Productos" asp-action="CrearProducto">Crear Nuevo Producto</a>
    </div>
  </div>
</div>
<table class="table ">
  <thead class="thead-dark text-center">
    <tr>
      <th scope="col">Número</th>
      <th scope="col">Imagen</th>
      <th scope="col">Nombre</th>
      <th scope="col">Precio</th>
      <th scope="col">Cantidad</th>
      <th class="text-center" scope="col">Acciones</th>
    </tr>
  </thead>
  <tbody class="text-center">
    <tr>
      <th>1</th>
      <td><img src="https://i5.walmartimages.com.mx/gr/images/product-images/img_large/00750649500407L.jpg?odnHeight=50&odnWidth=50&odnBg=FFFFFF" alt=""></td>
      <td>Atún</td>
      <td>$10.000</td>
      <td>10</td>
      <td>
        <a class="btn btn-danger" asp-controller="Productos" asp-action="EliminarProducto">Eliminar</a>
        <a class="btn btn-success" asp-controller="Productos" asp-action="EditarProducto">Editar</a>
        <a class="btn btn-info" asp-controller="Productos" asp-action="MostrarProducto">Detalles</a>
      </td>
    </tr>
    
  </tbody>
</table>

Views/Productos/MostrarProducto.cshtml
<div class="container">
    <div class="row justify-content-end">
        <div class="col-auto">
            <a  asp-controller="#" asp-action="#">Inicio</a>
        </div>
        <div class="col-auto">
            <a class="text-decoration-none text-black" asp-controller="#" asp-action="#">Gestion Usuario</a>
        </div>
    </div>
</div>

<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <img src="https://i5.walmartimages.com.mx/gr/images/product-images/img_large/00750649500407L.jpg?odnHeight=&odnWidth=&odnBg=FFFFFF" alt="">
                <div class="card-body text-center">
                    <p><b>Nombre:</b> Atún</p>
                    <p><b>Precio:</b> $10.000</p>
                    <p><b>Cantidad:</b> 10</p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container mt-3">
    <div class="row justify-content-center">
        <a type="button" class="btn btn-primary btn-lg w-25" asp-controller="Productos" asp-action="Index">Ver Lista Productos</a>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ejerciciosMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ejerciciosMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Dashboard" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Productos" asp-action="Index">Productos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="User" asp-action="Index">Usuarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Auth" asp-action="Index">Registrate</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ejerciciosMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/User/Actualizar.cshtml
<div class="container">
    <div class="row justify-content-end">
        <div class="col-auto">
            <a asp-controller="Dashboard" asp-action="Index">Inicio</a>
        </div>
        <div class="col-auto">
            <a class="text-decoration-none text-black" asp-controller="User" asp-action="Crear">Crear Nuevo Usuario</a>
        </div>
    </div>
</div>

<div class="container d-flex justify-content-center align-items-center">
    <div class="row">
        <div class="col-auto">
            <div class="card">
                <div class="card-body">
                    <h1>Se ha Actualizado con éxito el usuario</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container mt-3">
    <div class="row justify-content-center">
        <a type="button" class="btn btn-primary btn-lg w-25" asp-controller="User" asp-action="Index">Ver Lista Usuarios</a>
    </div>
</div>  

Views/User/Crear.cshtml
<div class="container">
    <div class="row justify-content-end">
        <div class="col-auto">
            <a asp-controller="Dashboard" asp-action="Index">Inicio</a>
        </div>
        <div class="col-auto">
            <a class="text-decoration-none text-black" asp-controller="#" asp-action="#">Crear Nuevo Usuario</a>
        </div>
    </div>
</div>

<form>
    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Nombre</label>
        <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Apellido</label>
        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Correo</label>
        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Genero</label>
        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Edad</label>
        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>
    <div class="mb-3 form-check">
        <input type="checkbox" class="form-check-input" id="exampleCheck1">
        <label class="form-check-label" for="exampleCheck1">Aceptas las Políticas</label>
    </div>
    <button type="submit" class="btn btn-primary">Crear Usuario</button>
</form>

Views/User/Editar.cshtml
<div class="container">
    <div class="row justify-content-end">
        <div class="col-auto">
            <a asp-controller="Dashboard" asp-action="Index">Inicio</a>
        </div>
        <div class="col-auto">
            <a class="text-decoration-none text-black" asp-controller="User" asp-action="Crear">Crear Nuevo Usuario</a>
        </div>
    </div>
</div>

<form>
    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Nombre</label>
        <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Apellido</label>
        <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Correo</label>
        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Genero</label>
        <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Edad</label>
        <input type="number" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>    
    <button type="submit" class="btn btn-primary" asp-controller="User" asp-action="Actualizar">Actualizar Usuario</button>
</form>

Views/User/Eliminar.cshtml
<div class="container">
    <div class="row justify-content-end">
        <div class="col-auto">
            <a asp-controller="Dashboard" asp-action="Index">Inicio</a>
        </div>
        <div class="col-auto">
            <a class="text-decoration-none text-black" asp-controller="User" asp-action="Crear">Crear Nuevo Usuario</a>
        </div>
    </div>
</div>

<div class="container d-flex justify-content-center align-items-center">
    <div class="row">
        <div class="col-auto">
            <div class="card">
                <div class="card-body">
                    <h1>Se ha eliminado con éxito el usuario</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container mt-3">
    <div class="row justify-content-center">
        <a type="button" class="btn btn-primary btn-lg w-25" asp-controller="User" asp-action="Index">Ver Lista Usuarios</a>
    </div>
</div>

Views/User/Index.cshtml
<div class="container">
  <div class="row justify-content-end">
    <div class="col-auto">
      <a asp-controller="Dashboard" asp-action="Index">Inicio</a>
    </div>
    <div class="col-auto">
      <a class="text-decoration-none text-black" asp-controller="#" asp-action="#"> Gestion Usuario</a>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col">
      <a class="btn btn-outline-primary" asp-controller="User" asp-action="Crear">Crear Nuevo Usuario</a>
    </div>
  </div>
</div>
<table class="table ">
  <thead class="thead-dark text-center">
    <tr>
      <th scope="col">Número</th>
      <th scope="col">Nombres</th>
      <th scope="col">Apellidos</th>
      <th scope="col">Correo</th>
      <th scope="col">Genero</th>
      <th scope="col">Edad</th>
      <th class="text-center" scope="col">Acciones</th>
    </tr>
  </thead>
  <tbody class="text-center">
    <tr>
      <th>1</th>
      <td>Robinson</td>
      <td>Cortes</td>
      <td>andres@gmail.com</td>
      <td>M</td>
      <td>30</td>
      <td>
        <a class="btn btn-danger" asp-controller="User" asp-action="Eliminar">Eliminar</a>
        <a class="btn btn-success" asp-controller="User" asp-action="Editar">Editar</a>
        <a class="btn btn-info" asp-controller="User" asp-action="Mostrar">Detalles</a>
      </td>
    </tr>
  </tbody>
</table>

Views/User/Mostrar.cshtml
<div class="container">
    <div class="row justify-content-end">
        <div class="col-auto">
            <a  asp-controller="#" asp-action="#">Inicio</a>
        </div>
        <div class="col-auto">
            <a class="text-decoration-none text-black" asp-controller="#" asp-action="#">Gestion Usuario</a>
        </div>
    </div>
</div>

<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body d-flex justify-content-around">
                    <div class="izquierda ">
                        <p><b>Nombres:</b> Daniel</p>
                        <p><b>Apellido:</b> Zapata</p>
                        <p><b>Edad:</b> 20</p>
                    </div>
                    <div class="derecha">
                        <p><b>Correo:</b>dani@example.com</p>
                        <p><b>Genero:</b> M</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container mt-3">
    <div class="row justify-content-center">
        <a type="button" class="btn btn-primary btn-lg w-25" asp-controller="User" asp-action="Index">Ver Lista Usuarios</a>
    </div>
</div>